### PR TITLE
Add dependencies present in requirements.txt to setup.py

### LINKED ISSUE #28: Follow-up from "Better logging"
In GitLab by @as6520 on Feb 17, 2021, 13:02

The following discussion from !59 should be addressed:

- [ ] @cfunk1210 started a [discussion](https://gitlab.kitware.com/darpa-sail-on/sail-on-client/-/merge_requests/59#note_893469): 

    > Should we add a warning here?

### PR DESCRIPTION
**Pull request by as6520**
This PR adds the dependencies present in requirements.txt back in setup.py. Originally this was removed because requirements.txt had absolute requirements rather than absolute requirements. This was changed in #85, thus we can add dependencies present in requirements.txt back into setup.py without running into version conflicts. Closes #28 since a warning isn't required anymore.

### CODE REVIEW

**Review by cfunk1210 — APPROVED** [review]
LGTM

**Comment by cfunk1210** [comment]
NVM, It breaks the install.

**Comment by as6520** [comment]
Defering to post eval since it is not critical.

**Review by Pikus16 — APPROVED** [review]

**Comment by as6520** [comment]
Closing since we are transitioning to poetry. Thus this is not relevant.

**Pull request closed without merging**
