### PR TITLE
Update condda

### PR DESCRIPTION
**Pull request by as6520**
This PR adds the code to update harness parameters in condda and copies a test from OND to CONDDA for dry run.

Depends on #119

### CODE REVIEW

**Review by cfunk1210 — COMMENTED** [review]
Why aren't you saving features the same way as #119 with the numpy encoder? 

What about the ` use_consolidated_features` for connda as well as ond.  

What about the `evaluate_round_wise` call.  This should be even more important to connda since we want to know the characterization (and matches the papers from Mohsen).


Does connda not have baseline?   How can we calculate reaction performance?

**Comment by as6520** [comment]
`use_consolidated_features` has been added in 2a77b01. Program metrics aren't defined for condda since there wasn't any consensus on characterization. One of the problem with `evaluate_round_wise` would be that NMI requires significantly more samples than 32 or the scores are unstable. We should talk to Terry and Mohsen about it if we want to implement these measures round wise

**Comment by cfunk1210** [comment]
Why are you saving the featues as a pickle for CONDDA and as a json for ond?  

The OWL: Open world learning paper from Terry's lab defines a metric that is more stable than NMI for low amounts of labels.  
Check you Equation 12 in https://arxiv.org/pdf/2011.12906.pdf
We should do a separate issue about adding it since not necessary yet.  

For now we can just use NMI though (even though we won't show it).  I think it's better to have it in here than to leave it out to keep the two protocols more similar (rather than adding it into condda in a later PR.

**Comment by cfunk1210** [comment]
Does connda not have baseline? How can we calculate reaction performance?  Can we calculate reaction performance for CONDDA?

**Comment by as6520** [comment]
> Why are you saving the featues as a pickle for CONDDA and as a json for ond?
Features are saved as json both in OND and CONDDA

**Comment by as6520** [comment]
> The OWL: Open world learning paper from Terry's lab defines a metric that is more stable than NMI for low amounts of labels.
> Check you Equation 12 in https://arxiv.org/pdf/2011.12906.pdf
> We should do a separate issue about adding it since not necessary yet.
> 
> For now we can just use NMI though (even though we won't show it). I think it's better to have it in here than to leave it out to keep the two protocols more similar (rather than adding it into condda in a later PR.

I can add it in a different PR as I said earlier, evaluation for CONDDA isn't defined that is why evaluate function isn't called in it

**Comment by as6520** [comment]
> Does connda not have baseline? How can we calculate reaction performance? Can we calculate reaction performance for CONDDA?

Yes CONDDA does not have a baseline or reaction performance computation. Since characterization isn't defined across domain, we don't have a way compute program metrics

**Comment by cfunk1210** [comment]
I thought they were saved here as a JSON: https://github.com/darpa-sail-on/sail-on-client/blob/master/sail_on_client/protocol/ond_protocol.py#L318

**Comment by cfunk1210** [comment]
For CONDDA, would characterization matter for reaction performance which is just on the known classes.

**Comment by as6520** [comment]
> I thought they were saved here as a JSON: https://github.com/darpa-sail-on/sail-on-client/blob/master/sail_on_client/protocol/ond_protocol.py#L318

The scores obtained from the metrics are saved in json, the features are saved in https://github.com/darpa-sail-on/sail-on-client/blob/master/sail_on_client/protocol/ond_protocol.py#L273

**Comment by as6520** [comment]
> For CONDDA, would characterization matter for reaction performance which is just on the known classes.

I don't think it can be called characterization if only known classes are being considered. Since the clusters would have 1-1 mapping, I think NMI would have the same interpretation as accuracy

**Comment by cfunk1210** [comment]
Are the CONDDA scores saved here?

**Comment by cfunk1210** [comment]
> > For CONDDA, would characterization matter for reaction performance which is just on the known classes.
> 
> I don't think it can be called characterization if only known classes are being considered. Since the clusters would have 1-1 mapping, I think NMI would have the same interpretation as accuracy

But we don't have a reaction to novelty accuracy for OND.  It's the known reaction to novelty score.

**Comment by as6520** [comment]
> > > For CONDDA, would characterization matter for reaction performance which is just on the known classes.
> > 
> > 
> > I don't think it can be called characterization if only known classes are being considered. Since the clusters would have 1-1 mapping, I think NMI would have the same interpretation as accuracy
> 
> But we don't have a reaction to novelty accuracy for OND. It's the known reaction to novelty score.

True we can use NMI pre-novelty and post-novelty. However it would just be accuracy since we expect 1-1 mapping for classes pre-novelty

**Comment by cfunk1210** [comment]
> > > > For CONDDA, would characterization matter for reaction performance which is just on the known classes.
> > > 
> > > 
> > > I don't think it can be called characterization if only known classes are being considered. Since the clusters would have 1-1 mapping, I think NMI would have the same interpretation as accuracy
> > 
> > 
> > But we don't have a reaction to novelty accuracy for OND. It's the known reaction to novelty score.
> 
> True we can use NMI pre-novelty and post-novelty. However it would just be accuracy since we expect 1-1 mapping for classes pre-novelty

That sounds fine to me

**Comment by cfunk1210** [comment]
> > I thought they were saved here as a JSON: https://github.com/darpa-sail-on/sail-on-client/blob/master/sail_on_client/protocol/ond_protocol.py#L318
> 
> The scores obtained from the metrics are saved in json, the features are saved in https://github.com/darpa-sail-on/sail-on-client/blob/master/sail_on_client/protocol/ond_protocol.py#L273

Are the CONNDA score written to a json?

**Comment by as6520** [comment]
> Are the CONNDA score written to a json?


No, evaluate isn't called in CONDDA since evaluate isn't defined for CONDDA.

**Comment by cfunk1210** [comment]
> > Are the CONNDA score written to a json?
> 
> No, evaluate isn't called in CONDDA since evaluate isn't defined for CONDDA.

So we don't have a self-eval for CONDDA

**Review by cfunk1210 — APPROVED** [review]
per my other comments, since we don't have an evaluation function here, this PR is fine for what it is.  

We should make an issue to add in CONDDA eval ASAP with Terry's metric so we can do self eval with CONDDA.

**Pull request merged**
