### PR TITLE
Transcription metric

### PR DESCRIPTION
**Pull request by as6520**
In GitLab by @as6520 on Feb 22, 2021, 08:10

This MR adds metric code for transcription domain.

### CODE REVIEW

**Comment by cfunk1210** [comment]
I'm having trouble launching this from the command line.  Looks like it is a problem with finding the test but unsure how to fix it.   

Error:
```
Traceback (most recent call last):
  File "/home/chris/code/sailon_tinker_launcher/hydra_launcher.py", line 16, in hydra_launcher
    launch_protocol.run_protocol(OmegaConf.to_container(cfg['problem']))
  File "/home/chris/code/sailon_tinker_launcher/sailon_tinker_launcher/main.py", line 197, in run_protocol
    run_protocol.run_protocol()
  File "/home/chris/code/sail-on-client/sail_on_client/protocol/ond_protocol.py", line 68, in run_protocol
    self.config["hints"],
  File "/home/chris/code/sail-on-client/sail_on_client/protocol/localinterface.py", line 90, in session_request
    test_ids, protocol, domain, novelty_detector_version, hints
  File "/home/chris/code/sail-on-api/sail_on/api/file_provider.py", line 408, in new_session
    traceback.format_stack(),
sail_on.api.errors.ServerError: ('test_id_invalid', 'Test Id OND.0.90001.8714062 could not be matched to a specific file', ['  File "/home/chris/code/sailon_tinker_launcher/hydra_launcher.py", line 20, in <module>\n    hydra_launcher()\n', '  File "/home/chris/anaconda3/envs/sailon/lib/python3.7/site-packages/hydra/main.py", line 37, in decorated_main\n    strict=strict,\n', '  File "/home/chris/anaconda3/envs/sailon/lib/python3.7/site-packages/hydra/_internal/utils.py", line 347, in _run_hydra\n    lambda: hydra.run(\n', '  File "/home/chris/anaconda3/envs/sailon/lib/python3.7/site-packages/hydra/_internal/utils.py", line 198, in run_and_report\n    return func()\n', '  File "/home/chris/anaconda3/envs/sailon/lib/python3.7/site-packages/hydra/_internal/utils.py", line 350, in <lambda>\n    overrides=args.overrides,\n', '  File "/home/chris/anaconda3/envs/sailon/lib/python3.7/site-packages/hydra/_internal/hydra.py", line 112, in run\n    configure_logging=with_log_configuration,\n', '  File "/home/chris/anaconda3/envs/sailon/lib/python3.7/site-packages/hydra/core/utils.py", line 128, in run_job\n    ret.return_value = task_function(task_cfg)\n', '  File "/home/chris/code/sailon_tinker_launcher/hydra_launcher.py", line 16, in hydra_launcher\n    launch_protocol.run_protocol(OmegaConf.to_container(cfg[\'problem\']))\n', '  File "/home/chris/code/sailon_tinker_launcher/sailon_tinker_launcher/main.py", line 197, in run_protocol\n    run_protocol.run_protocol()\n', '  File "/home/chris/code/sail-on-client/sail_on_client/protocol/ond_protocol.py", line 68, in run_protocol\n    self.config["hints"],\n', '  File "/home/chris/code/sail-on-client/sail_on_client/protocol/localinterface.py", line 90, in session_request\n    test_ids, protocol, domain, novelty_detector_version, hints\n', '  File "/home/chris/code/sail-on-api/sail_on/api/file_provider.py", line 408, in new_session\n    traceback.format_stack(),\n'])

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.
```

config

```
Config: 
{
    "domain": "transcripts",
    "test_ids": [
        "OND.0.90001.8714062"
    ],
    "novelty_detector_class": "HWRNoveltyDetector",
    "seed": "seed",
    "dataset_root": "/mnt/3bcbbdb5-8833-4d40-a51a-7fca7f39ec24/data2/sailon_data/TA1/TA1-transcription/images/",
    "feature_extraction_only": false,
    "use_feedback": false,
    "save_features": false,
    "use_saved_features": false,
    "save_dir": "",
    "save_attributes": false,
    "use_saved_attributes": false,
    "save_elementwise": false,
    "saved_attributes": {},
    "skip_stage": [],
    "hints": [],
    "detector_config": {
        "config_file_path": "/home/chris/code/sailon_tinker_launcher/configs/extra_configs/hwr_config.yaml",
        "cores": 1,
        "device": "gpu",
        "csv_folder": "/home/chris/code/sailon_tinker_launcher/workdir/0f996bc28a47b8ce",
        "img_height": 64,
        "hogs_ppc": 16,
        "unknown_threshold": 0.5,
        "crnn_pass": [],
        "save_header_csv": 0
    }
}
```

configuration.json
```
{
  "url": "http://3.32.8.161:5001/",
  "data_location": "/mnt/3bcbbdb5-8833-4d40-a51a-7fca7f39ec24/data2/sailon_data/TA1/TA1-transcription/images/",
  "data_dir": "/home/chris/code/sail-on-client/tests/data/OND/transcripts",
  "gt_dir": "/home/chris/code/sail-on-client/tests/data/OND/transcripts/",
  "gt_config": "/home/chris/code/sail-on-client/tests/data/OND/transcripts/transcripts.json"
}
```
```

**Comment by cfunk1210** [comment]
Also, can we print out the stack trace rather than printing the line formats inline?

**Comment by as6520** [comment]
It looks like the data_dir is set incorrectly in configuration.json. It should be `/home/chris/code/sail-on-client/tests/data`

**Comment by as6520** [comment]
`Also, can we print out the stack trace rather than printing the line formats inline?
`
Not sure since the error object is present, could you file an issue in the sail on API and ping @edvax / @rwgdrummer about it on the issue?

**Review by cfunk1210 — APPROVED** [review]
LGTM

**Pull request merged**
