### PR TITLE
Add writer identification baseline

### PR DESCRIPTION
**Pull request by as6520**
This PR adds writer identification baseline and novelty reaction performance for novelty reaction. Depends on #83

### CODE REVIEW

**Comment by as6520** [comment]
Looked at the CI failure it is originating from sail on api, refer to https://github.com/darpa-sail-on/Sail-On-API/issues/11 for more details.

**Comment by as6520** [comment]
Rebased on #88 to see if that would fix the CI failures.

**Review by nrsyed — DISMISSED** [review]
LGTM

**Comment by as6520** [comment]
Had to rebase on the master to fix the merge conflict, @nrsyed could you please approve the PR again?

**Review by nrsyed — APPROVED** [review]

**Pull request merged**
